library(quantmod)
datasymbols=c("AMZN","TSLA","BRK-B","SPY")
getSymbols(datasymbols,src='yahoo')
summary(`AMZN`)
AMZN=as.xts(`AMZN`)
names(AMZN)=c("AMZN.Open","AMZN.High","AMZN.Low","AMZN.Close","AMZN.Volume","AMZN.Adjusted")
plot(AMZN$AMZN.High)
lineChart(AMZN,line.type = "l")
candleChart(AMZN,subset = 'last 3 months',TA=NULL,theme = "white")
candleChart(AMZN,subset="last 3 months",TA=c(addMACD(),addVo()))
